services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_container
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ..
        target: /workspace
        bind:
          create_host_path: false
      - type: volume
        target: /workspace/node_modules
    tty: true
    command: ["sleep", "infinity"]
  db:
    image: postgres:16.8-bookworm
    container_name: "db_container"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/postgresql/data
      - type: bind
        source: ../initdb
        target: /docker-entrypoint-initdb.d

volumes:
  db-data:

